### PR TITLE
fix: modify CONTRIBUTORS.md and README.md file.

### PR DESCRIPTION
**Pull request by BeautifulMoon211**
Please review my pull request ASAP.
Thank you.

### CODE REVIEW

**Comment by AvidCoder101** [comment]
Hi @BeautifulMoon211 thanks for contributing! The modification of the README.md is for a bot to complete, and please could you remove that commit? Then I can merge the PR and add you to the organisation. Thanks :)

**Review by AvidCoder101 — APPROVED** [review]

**Comment by BeautifulMoon211** [comment]
Hi, I hope you are doing well.
I updated my PR and plz merge.
Thank you. Regards

**Comment by AvidCoder101** [comment]
@BeautifulMoon211 Thanks for contributing! I have sent an invitation to the org

**Comment by AvidCoder101** [comment]
@all-contributors please add @BeautifulMoon211 for content

**Comment by BeautifulMoon211** [comment]
Awesome, thank you so much!

**Pull request merged**
