### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shinevue**
I have made some changes. Please review. Thanks

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@shinevue Hi, thanks for contributing! Seems like you have edited the all-contributors file, which shouldn't be changed because this is complete by a bot. Please could you remove the commits that affect this? Thanks

**Review by AvidCoder101 — CHANGES_REQUESTED** [review]
Please remove this commit

**Comment by shinevue** [comment]
Ok, thank you

**Comment by shinevue** [comment]
I got it

**Comment by AvidCoder101** [comment]
@shinevue Thanks for your collaboration! You have been invited to the organisation

**Comment by AvidCoder101** [comment]
@all-contributors please add @shinevue for content

**Pull request merged**
