### PR TITLE
Hey Its Akshat Mittal

### PR DESCRIPTION
**Pull request by akshatmittal61**
Add [Akshat Mittal](https://github.com/akshatmittal61) as a contributor.

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
Thank you for contributing @akshatmittal61 ! This looks good.
Let's see what @AvidCoder101 says.
Thank you.

**Comment by CodingSpecies** [comment]
As you have contributed @akshatmittal61 , I have sent you an invite to this organisation. Feel free to accept, and set your organisation status as public, so it is visible on your Github profile. Use this link, and it will take you to the organisation page, where a banner will display the invite - [https://github.com/CodingContributorsLair](https://github.com/CodingContributorsLair) or see your emails. Thank you!

**Review by AvidCoder101 — APPROVED** [review]
@akshatmittal61 thanks for contributing to the organisation  🎉 Glad to see that you have joined the organisation. Feel free to contribute to any other of our repos 🙂

**Comment by AvidCoder101** [comment]
@all-contributors please add @akshatmittal61 for content

**Pull request merged**
