### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Bikram-ghuku**

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@Bikram-ghuku apologies for the delay in review.

**Review by AvidCoder101 — CHANGES_REQUESTED** [review]
Could you please add the link to your profile, which would be https://github.com/Bikram-ghuku

**Comment by AvidCoder101** [comment]
Doing this change will allow me to merge the PR and invite you to the organisation

**Comment by Bikram-ghuku** [comment]
> Doing this change will allow me to merge the PR and invite you to the organisation

I am creating a new PR

**Pull request closed without merging**
