### PR TITLE
Hey its Sneha Sharma

### PR DESCRIPTION
**Pull request by snehasharma1111**

### CODE REVIEW

**Review by d-coder111 — APPROVED** [review]
Seems okay

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Hey sneha, I think you have entered your name twice so kindly remove the duplicate entry.

**Review by AvidCoder101 — CHANGES_REQUESTED** [review]
@snehasharma1111 please could you remove the duplicate name? That way we could merge the PR and then invite you to the org. Thanks (:

**Comment by AvidCoder101** [comment]
If you need help, please let us know 🙂

**Comment by snehasharma1111** [comment]
Can you please check now?

**Review by AvidCoder101 — APPROVED** [review]
@snehasharma1111 Thanks for the changes, I have added you to the organisation and please remember to make your membership public

**Comment by AvidCoder101** [comment]
@all-contributors please add @snehasharma1111 for content

**Pull request merged**
