### PR TITLE
I have added my changes

### PR DESCRIPTION
**Pull request by Alamin0x01**
I have mode some changes. Please review. thank you

### CODE REVIEW

**Review by AvidCoder101 — APPROVED** [review]
@Alamin0x01 Thanks for contributing! I have sent you an invitation to the organisation 🙂

**Comment by AvidCoder101** [comment]
@all-contributors please add @Alamin0x01 for content

**Review by Alamin0x01 — COMMENTED** [review]
_**all OK**_

**Comment by Alamin0x01** [comment]
Thanks🤍

**Pull request merged**
