### PR TITLE
Add ahmadhassan7 in CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by ahmadhassan7**
PR made

### CODE REVIEW

**Review by AvidCoder101 — CHANGES_REQUESTED** [review]
@ahmadhassan7 Thanks for contributing! Please add your name to the end of the file.

**Review by ahmadhassan7 — COMMENTED** [review]
Change has been made

**Review by AvidCoder101 — APPROVED** [review]

**Comment by AvidCoder101** [comment]
@ahmadhassan7 I have sent you an invite to the organisation. Please remember to turn your membership to public. Welcome 🙂

**Comment by AvidCoder101** [comment]
@all-contributors please add @ahmadhassan7 for content

**Pull request merged**
